ktor:
    application:
        modules:
            - fi.lipp.blog.ApplicationKt.module
    deployment:
        port: 80
jwt:
    issuer: "blog application"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "pupa"
mail:
    host: "host"
    port: ""
    email: ""
    password: ""
    from: ""
directory:
    avatars: "{userLogin}/avatars"
    images: "{userLogin}/images"
    videos: "{userLogin}/videos"
    audios: "{userLogin}/audios"
    styles: "{userLogin}/styles"
    other: "{userLogin}/other"
url:
    avatars: "???"
    images: "???"
    videos: "???"
    audios: "???"
    styles: "???"
    other: "???"
