ktor:
    application:
        modules:
            - fi.lipp.blog.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    issuer: "blog application"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "pupa"
mail:
    host: "host"
    port: ""
    email: ""
    password: ""
    from: ""
directory:
    avatars: "{userLogin}/avatars"
    images: "{userLogin}/images"
    videos: "{userLogin}/videos"
    audios: "{userLogin}/audios"
    styles: "{userLogin}/styles"
    other: "{userLogin}/other"
    reactions: "{userLogin}/reactions"
url:
    avatars: "???"
    images: "???"
    videos: "???"
    audios: "???"
    styles: "???"
    other: "???"
    reactions: "???"
reactions:
    basic: ["like", "love", "haha", "wow", "sad", "angry"]
storage:
    quota:
        basic: 8
        standard: 16
        max: 32
