ktor:
    application:
        modules:
            - fi.lipp.blog.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    issuer: "blog application"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "pupa"
mail:
    host: "host"
    port: ""
    email: ""
    password: ""
    from: ""
    api-key: ""
geoip:
    database: "/path/to/GeoLite2-City.mmdb"
storage:
    base_dir: "/tmp"
    base_url: "http://localhost:8000"
    use_cdn: false
    cdn_base_url: ""
    cdn_api_key: ""
reactions:
    basic: ["like", "love", "haha", "wow", "sad", "angry"]